### ISSUE TITLE
Snap/Fit to edges?

### ISSUE THREAD

**Issue by Crayder** [Y-Less/PaperRound#1]
Well I'm working with large pictures, and it's inconvenient to hold the '--' buttons until the image fits. Then after I do hold it after the prolonged time, I like the edges to be aligned since I actually split the image in half to each half on another monitor.

So two suggestions.
1. A button to fit images to the window.
2. A snap to edges toggle, to automatically align the images to the edges when near.

**Comment by Y-Less** [comment]
Yes, some way to do that would be good, but I'm unlikely to modify it any time soon sorry.

**Comment by Y-Less** [comment]
OK, I lied - I realised it would be much simpler than I thought, so I did it!

**Comment by Crayder** [comment]
It works! Now some tooltips would be nice.

**Comment by Y-Less** [comment]
Yes they would, but I didn't do them as the whole thing is already pretty simple, and the documentation covers every feature.

**Comment by Crayder** [comment]
Point taken

**Comment by Y-Less** [comment]
Frankly I should - WPF has native support for them so it is literally an extra parameter on each button...

**Comment by Y-Less** [comment]
I'll stop turning down, then doing, requests some day; and either just do them initially or turn them down and not do them at all...

**Comment by Crayder** [comment]
Yeah I was thinking the same thing... XD
